### ISSUE TITLE
doc: add instruction in firebase to enable sign in and firestore database

### ISSUE THREAD

**Issue by jaiakash** [aashishvanand/ccreward-web#67]
Hi @aashishvanand , While setting up the project, I encountered some issues, particularly with the Firebase setup:

- Firestore database access needs to be enabled in the Firebase console to save or retrieve any data.
- Authentication must be enabled in the Firebase console to allow any kind of login (neither anonymous nor Google OAuth works without this).

I suggest adding these instructions to the README for proper project setup.

**Comment by jaiakash** [comment]
@aashishvanand any update on this issue?

**Comment by aashishvanand** [comment]
@jaiakash, I have added instructions. Check and let me know
