### ISSUE TITLE
fix: use new x icon on landing page for X/Twitter of testimonials

### ISSUE THREAD

**Issue by jaiakash** [aashishvanand/ccreward-web#68]
The landing page uses the old bird icon for Twitter. Don't you think we should use the new icon for Twitter/X?

Something like this.
<img width="1260" alt="Screenshot 2024-10-23 at 4 22 50 AM" src="https://github.com/user-attachments/assets/d276c2c3-9cca-45e5-9448-d82e9d18e2e3">

**Comment by aashishvanand** [comment]
Hi @jaiakash, Thanks for bringing this up! Its Fixed
